services:
  agent:
    image: sinanozel/ai-assistent:0.1.0
    ports:
      - "8000:8000"
    volumes:
      - ./cortex:/app/cortex
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    depends_on:
      - redis
      - qdrant

  redis:
    image: redis:7-alpine

  qdrant:
    image: qdrant/qdrant:v1.12.1
