services:
  agent:
    image: sinanozel/ai-assistent:0.1.0
    ports:
      - "8000:8000"
    volumes:
      - ./cortex:/app/cortex
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    depends_on:
      - redis
      - qdrant
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2500M
        reservations:
          cpus: "0.25"
          memory: 1G
  redis:
    image: redis:7-alpine
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
        reservations:
          cpus: "0.10"
          memory: 128M
  qdrant:
    image: qdrant/qdrant:v1.12.1
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.10"
          memory: 256M
