apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-assistant.fullname" . }}
  labels:
    {{- include "ai-assistant.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "ai-assistant.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
  ports:
    {{- if .Values.ports.fastapi }}
    - name: http
      port: {{ .Values.ports.fastapi }}
      targetPort: http
      protocol: TCP
    {{- end }}
    {{- if .Values.ports.streamlit }}
    - name: streamlit
      port: {{ .Values.ports.streamlit }}
      targetPort: streamlit
      protocol: TCP
    {{- end }}
