services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: devcontainer
    volumes:
      - ..:/workspace
    working_dir: /workspace
    command: sleep infinity
    networks:
      - agent-dev-network
    depends_on:
      - redis
      - qdrant
      - embedding

  redis:
    image: redis:7.4.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes
    networks:
      - agent-dev-network

  qdrant:
    image: qdrant/qdrant:v1.12.1
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data/qdrant:/qdrant/storage
    networks:
      - agent-dev-network

  embedding:
    image: sinanozel/ollama.0.12.11:all-minilm-33m
    container_name: embedding
    ports:
      - "11434:11434"
    networks:
      - agent-dev-network

networks:
  agent-dev-network:
    driver: bridge
