"""OpenAPI contract tests using pytest-openapi.

This test uses the pytest-openapi plugin to validate the API against its OpenAPI spec.
Run with: pytest --openapi=http://app:8000 test_openapi_contract.py
"""
import os

import pytest

BASE_URL = os.getenv("BASE_URL", "http://app:8000")


@pytest.mark.depends(on=["test_health_endpoint.py::test_health_endpoint"])
def test_openapi_contract():
    """Placeholder test that will be replaced by pytest-openapi generated tests.

    When running with --openapi flag, pytest-openapi will automatically discover
    and test all endpoints defined in the OpenAPI specification.
    """
    # This test exists only to ensure pytest discovers this file
    # The actual tests are generated by pytest-openapi
    assert True
