services:
  agent-stem-dev:
    build:
      context: ..
      dockerfile: agent_stem/Dockerfile
    container_name: agent-stem-dev
    volumes:
      - ..:/workspace
      - ${AGENT_FOLDER:-./cortex}:/app/cortex
    working_dir: /workspace
    ports:
      - "8000:8000"
      - "8501:8501"
      - "11434:11434"
    environment:
      - EMBEDDING_SERVER=http://embedding:11434
      - EMBEDDING_TIMEOUT=8.0
      - MCP_BUSINESS_HOURS_URL=http://business-hours:8000
      # - CONVERSATION_WINDOW_LIMIT=4096
      # - LOG_LEVEL=DEBUG
    env_file:
      - .env
    networks:
      - agent-dev-network
    depends_on:
      - redis
      - qdrant
      - embedding
      - business-hours

  redis:
    image: redis:7.4.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ${DEV_DATA_FOLDER:-./dev-data}/redis:/data
    command: redis-server
    networks:
      - agent-dev-network

  qdrant:
    image: qdrant/qdrant:v1.12.1
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ${DEV_DATA_FOLDER:-./dev-data}/qdrant:/qdrant/storage
    networks:
      - agent-dev-network

  embedding:
    image: sinanozel/ollama.0.12.11:all-minilm-33m
    container_name: embedding
    networks:
      - agent-dev-network

  llamacpp:
    image: sinanozel/llama.cuda:qwen3-0.6b
    networks:
      - agent-dev-network
    # command: ["-m", "/models/model.gguf", "--host", "0.0.0.0", "--port", "8080", "-ngl", "999", "-c", "4096", "--no-jinja"]
    deploy:
      resources:
        reservations:
          memory: 1G
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 120s

  ollama:
    image: sinanozel/ollama.0.12.11:gemma3-270m
    container_name: ollama
    networks:
      - agent-dev-network
    deploy:
      resources:
        reservations:
          memory: 1G
    healthcheck:
      test: ["CMD-SHELL", "timeout 10s bash -c ':> /dev/tcp/127.0.0.1/11434' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  eberron-mcp-server:
    image: sinanozel/eberron-mcp-server:0.1.2
    container_name: eberron-mcp-server
    networks:
      - agent-dev-network
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  business-hours:
    image: sinanozel/business-hours-mcp:0.1.0
    environment:
      - TIMEZONE=America/New_York
      - HOURS_MON=closed
      - HOURS_TUE=08:00-18:00
      - HOURS_WED=08:00-18:00
      - HOURS_THU=08:00-18:00
      - HOURS_FRI=08:00-18:00
      - HOURS_SAT=08:00-18:00
      - HOURS_SUN=08:00-18:00
    networks:
      - agent-dev-network


networks:
  agent-dev-network:
    driver: bridge
